DEL "iBSS.n72ap.RELEASE.dfu" /f /q
DEL "iBSS.n72ap.RELEASE.payload" /f /q
DEL "iBSS.n72ap.RELEASE.d" /f /q
DEL "iBEC.n72ap.RELEASE.d" /f /q
DEL "iBEC.n72ap.RELEASE.pwned" /f /q
DEL "iBEC.n72ap.RELEASE.semipwned" /f /q
DEL "iBEC.n72ap.RELEASE.semisemipwned" /f /q
DEL "iBEC.n72ap.RELEASE.dfu" /f /q
DEL "iBSS.n82ap.RELEASE.dfu" /f /q
DEL "iBSS.n82ap.RELEASE.payload" /f /q
DEL "iBSS.n82ap.RELEASE.d" /f /q
DEL "iBEC.n82ap.RELEASE.d" /f /q
DEL "iBEC.n82ap.RELEASE.pwned" /f /q
DEL "iBEC.n82ap.RELEASE.semipwned" /f /q
DEL "iBEC.n82ap.RELEASE.dfu" /f /q
DEL "WTF.s5l8900xall.RELEASE.dfu" /f /q
DEL "itunnel.exe" /f /q
DEL "wait.img3" /f /q
DEL "ipt2g.exe" /f /q
DEL "3G.exe" /f /q
DEL "unzip.exe" /f /q
DEL "Resources.zip" /f /q
DEL "msvcr100d.dll" /f /q
DEL "pois0n.exe" /f /q
